// Mock 데이터 정의

export const mockPendingUsers = [
  {
    userId: 1,
    name: '김철수',
    phone: '010-1234-5678',
    createdAt: '2025-01-10T09:30:00',
    status: 'PENDING',
    uid: 'UID-2025-001',
  },
  {
    userId: 2,
    name: '이영희',
    phone: '010-2345-6789',
    createdAt: '2025-01-11T14:20:00',
    status: 'PENDING',
    uid: 'UID-2025-002',
  },
  {
    userId: 3,
    name: '박민준',
    phone: '010-3456-7890',
    createdAt: '2025-01-12T11:15:00',
    status: 'APPROVED',
    uid: 'UID-2025-003',
  },
];

export const mockConsultations = [
  {
    id: 1,
    customerName: '최지훈',
    customerPhoneNumber: '010-4567-8901',
    date: '2025-01-20',
    time: { hour: 15, minute: 0, second: 0, nano: 0 },
    createdAt: '2025-01-10T10:00:00',
    isProcessed: false,
    memo: '상담 시간 변경 요청',
  },
  {
    id: 2,
    customerName: '강서연',
    customerPhoneNumber: '010-5678-9012',
    date: '2025-01-21',
    time: { hour: 14, minute: 0, second: 0, nano: 0 },
    createdAt: '2025-01-11T09:30:00',
    isProcessed: true,
    memo: '레벨테스트 관련 상담 완료',
  },
  {
    id: 3,
    customerName: '윤도현',
    customerPhoneNumber: '010-6789-0123',
    date: '2025-01-22',
    time: { hour: 10, minute: 0, second: 0, nano: 0 },
    createdAt: '2025-01-12T16:20:00',
    isProcessed: false,
    memo: '',
  },
  {
    id: 4,
    customerName: '박민지',
    customerPhoneNumber: '010-7890-1234',
    date: '2025-01-23',
    time: { hour: 16, minute: 30, second: 0, nano: 0 },
    createdAt: '2025-01-13T11:15:00',
    isProcessed: false,
    memo: '첫 상담 - 투자 성향 파악',
  },
];

export const mockManagedCustomers = [
  {
    customerId: 1,
    customerName: '정수민',
    phone: '010-7890-1234',
    investmentType: '스윙',
    lastLevelTest: 'A등급',
    trainerName: '이코치',
    levelTestStatus: '응시완료',
    hasConsultation: true,
  },
  {
    customerId: 2,
    customerName: '임하늘',
    phone: '010-8901-2345',
    investmentType: '데이',
    lastLevelTest: 'B등급',
    trainerName: '박코치',
    levelTestStatus: '미응시',
    hasConsultation: false,
  },
  {
    customerId: 3,
    customerName: '송지우',
    phone: '010-9012-3456',
    investmentType: '스윙',
    lastLevelTest: 'A+등급',
    trainerName: '김코치',
    levelTestStatus: '응시완료',
    hasConsultation: true,
  },
];

export const mockFeedbackRequests = [
  {
    feedbackId: 1,
    customerName: '한지수',
    trainerName: '이코치',
    tradingType: 'SWING',
    requestDate: '2025-01-10T09:00:00',
    status: 'PENDING',
    isBest: false,
  },
  {
    feedbackId: 2,
    customerName: '오세훈',
    trainerName: '박코치',
    tradingType: 'DAY',
    requestDate: '2025-01-11T10:30:00',
    status: 'COMPLETED',
    isBest: true,
  },
  {
    feedbackId: 3,
    customerName: '신예은',
    trainerName: '김코치',
    tradingType: 'SWING',
    requestDate: '2025-01-12T14:00:00',
    status: 'PENDING',
    isBest: false,
  },
  {
    feedbackId: 4,
    customerName: '이준호',
    trainerName: '이코치',
    tradingType: 'SCALPING',
    requestDate: '2025-01-13T15:20:00',
    status: 'COMPLETED',
    isBest: true,
  },
  {
    feedbackId: 5,
    customerName: '박서연',
    trainerName: '박코치',
    tradingType: 'DAY',
    requestDate: '2025-01-14T11:00:00',
    status: 'COMPLETED',
    isBest: false,
  },
  {
    feedbackId: 6,
    customerName: '최민수',
    trainerName: '김코치',
    tradingType: 'SWING',
    requestDate: '2025-01-15T09:30:00',
    status: 'COMPLETED',
    isBest: true,
  },
  {
    feedbackId: 7,
    customerName: '정하은',
    trainerName: '이코치',
    tradingType: 'DAY',
    requestDate: '2025-01-16T14:00:00',
    status: 'COMPLETED',
    isBest: false,
  },
  {
    feedbackId: 8,
    customerName: '강태우',
    trainerName: '박코치',
    tradingType: 'SCALPING',
    requestDate: '2025-01-17T10:15:00',
    status: 'COMPLETED',
    isBest: false,
  },
  {
    feedbackId: 9,
    customerName: '윤지아',
    trainerName: '김코치',
    tradingType: 'SWING',
    requestDate: '2025-01-18T16:30:00',
    status: 'PENDING',
    isBest: false,
  },
  {
    feedbackId: 10,
    customerName: '서동현',
    trainerName: '이코치',
    tradingType: 'DAY',
    requestDate: '2025-01-19T13:45:00',
    status: 'COMPLETED',
    isBest: false,
  },
];

export const mockComplaints = [
  {
    complaintId: 1,
    customerName: '박서준',
    phone: '010-1111-2222',
    trainerName: '이코치',
    content: '피드백 응답 시간이 너무 오래 걸립니다. 24시간 이내 답변을 받기로 했는데 2일이 지났습니다.',
    images: [],
    reply: '불편을 드려 죄송합니다. 담당 트레이너에게 빠른 응답을 요청했으며, 앞으로는 24시간 이내 응답을 보장하겠습니다.',
    replyAuthor: '관리자',
    replyCreatedAt: '2025-01-11T10:00:00',
    createdAt: '2025-01-10T15:30:00',
  },
  {
    complaintId: 2,
    customerName: '이채영',
    phone: '010-3333-4444',
    trainerName: '박코치',
    content: '레벨테스트 결과에 대한 피드백이 부족합니다. 좀 더 상세한 설명이 필요합니다.',
    images: [],
    reply: '',
    replyAuthor: '',
    replyCreatedAt: '',
    createdAt: '2025-01-12T11:20:00',
  },
  {
    complaintId: 3,
    customerName: '최민석',
    phone: '010-5555-6666',
    trainerName: '김코치',
    content: '상담 일정이 갑자기 변경되어 불편했습니다. 사전에 알려주셨으면 좋겠습니다.',
    images: [],
    reply: '상담 일정 변경으로 불편을 드려 죄송합니다. 앞으로는 최소 1일 전에 알려드리도록 하겠습니다.',
    replyAuthor: '관리자',
    replyCreatedAt: '2025-01-12T16:00:00',
    createdAt: '2025-01-12T09:45:00',
  },
  {
    complaintId: 4,
    customerName: '김나연',
    phone: '010-7777-8888',
    trainerName: '이코치',
    content: '강의 자료가 잘 보이지 않습니다. PDF 파일을 다시 확인해주세요.',
    images: [],
    reply: '',
    replyAuthor: '',
    replyCreatedAt: '',
    createdAt: '2025-01-13T14:10:00',
  },
];

export const mockComplaintDetail = (id: number) => {
  const complaint = mockComplaints.find((c) => c.complaintId === id);
  if (!complaint) return null;

  return {
    ...complaint,
    images: id === 1 ? [] : [],
  };
};

export const mockMonthlyTradingSummary = {
  customerId: 1,
  year: 2025,
  month: 1,
  dayTrading: {
    totalCount: 15,
    profitCount: 10,
    lossCount: 5,
    profitRate: 66.7,
  },
  swingTrading: {
    totalCount: 8,
    profitCount: 6,
    lossCount: 2,
    profitRate: 75.0,
  },
};

export const mockTrainers = [
  {
    trainerId: 1,
    profileImageUrl: '',
    name: '이코치',
    phone: '01012345678',
    onelineIntroduction: '스윙 트레이딩 전문 트레이너',
    username: 'trainer_lee',
    role: 'ROLE_TRAINER',
  },
  {
    trainerId: 2,
    profileImageUrl: '',
    name: '박코치',
    phone: '01023456789',
    onelineIntroduction: '데이 트레이딩 전문가',
    username: 'trainer_park',
    role: 'ROLE_TRAINER',
  },
  {
    trainerId: 3,
    profileImageUrl: '',
    name: '김관리자',
    phone: '01034567890',
    onelineIntroduction: '시스템 관리자',
    username: 'admin_kim',
    role: 'ROLE_ADMIN',
  },
];

export const mockAssignedCustomers = [
  {
    customerId: 1,
    name: '정수민',
  },
  {
    customerId: 2,
    name: '임하늘',
  },
  {
    customerId: 3,
    name: '송지우',
  },
];

export const mockReviews = [
  {
    id: 1,
    customerId: 1,
    customerName: '정수민',
    content: '트레이딩 PT를 시작한 지 3개월이 되었습니다. 처음에는 손실이 많았지만 꾸준한 피드백 덕분에 이제는 안정적으로 수익을 내고 있습니다. 특히 리스크 관리 부분이 많이 개선되었어요.',
    submittedAt: '2025-01-15T10:30:00',
    trainerReply: {
      trainerId: 1,
      replyContent: '3개월 동안 정말 열심히 하셨습니다! 앞으로도 리스크 관리를 철저히 하시면 좋은 결과가 있을 것입니다.',
      repliedAt: '2025-01-15T14:20:00',
    },
    isPublic: true,
  },
  {
    id: 2,
    customerId: 2,
    customerName: '임하늘',
    content: '데이 트레이딩 전략을 배우면서 손절의 중요성을 깨달았습니다. 담당 트레이너님의 세심한 지도 덕분에 매매 실력이 많이 향상되었습니다.',
    submittedAt: '2025-01-14T16:45:00',
    trainerReply: undefined,
    isPublic: true,
  },
  {
    id: 3,
    customerId: 3,
    customerName: '송지우',
    content: '스윙 트레이딩 방식이 제 성격에 잘 맞는 것 같습니다. 장기적인 관점에서 투자하는 방법을 배워서 좋았습니다.',
    submittedAt: '2025-01-13T11:20:00',
    trainerReply: {
      trainerId: 2,
      replyContent: '스윙 트레이딩에 적응을 잘 하고 계시네요. 계속해서 종목 분석과 진입/청산 타이밍을 연습하시면 더 좋은 결과가 있을 겁니다.',
      repliedAt: '2025-01-13T15:30:00',
    },
    isPublic: false,
  },
  {
    id: 4,
    customerId: 4,
    customerName: '김민준',
    content: '초보자도 이해하기 쉽게 설명해주셔서 감사합니다. 레벨테스트 피드백도 상세해서 제 약점을 보완할 수 있었습니다.',
    submittedAt: '2025-01-12T09:15:00',
    trainerReply: undefined,
    isPublic: true,
  },
];

export const mockInvestmentChangeRequests = [
  {
    id: 1,
    customerId: 1,
    customerName: '정수민',
    currentType: 'SWING' as const,
    requestedType: 'DAY' as const,
    status: 'PENDING' as const,
    reason: '스윙 트레이딩에서 데이 트레이딩으로 변경하고 싶습니다. 시장 변동성이 커서 단기 매매가 더 적합하다고 판단했습니다.',
    requestedDate: '2025-01-10',
    targetChangeDate: '2025-02-01',
    processedAt: undefined,
    approvedByName: undefined,
    rejectionReason: undefined,
  },
  {
    id: 2,
    customerId: 2,
    customerName: '임하늘',
    currentType: 'DAY' as const,
    requestedType: 'SCALPING' as const,
    status: 'PENDING' as const,
    reason: '더 빠른 매매 기회를 포착하고 싶어서 스켈핑으로 변경 신청합니다.',
    requestedDate: '2025-01-12',
    targetChangeDate: '2025-02-05',
    processedAt: undefined,
    approvedByName: undefined,
    rejectionReason: undefined,
  },
  {
    id: 3,
    customerId: 3,
    customerName: '송지우',
    currentType: 'SCALPING' as const,
    requestedType: 'SWING' as const,
    status: 'APPROVED' as const,
    reason: '스켈핑이 제 성향에 맞지 않아 스윙으로 변경하고자 합니다.',
    requestedDate: '2025-01-05',
    targetChangeDate: '2025-01-20',
    processedAt: '2025-01-06T10:30:00',
    approvedByName: '이코치',
    rejectionReason: undefined,
  },
  {
    id: 4,
    customerId: 4,
    customerName: '김민준',
    currentType: 'DAY' as const,
    requestedType: 'SWING' as const,
    status: 'REJECTED' as const,
    reason: '데이 트레이딩에서 스윙으로 변경 요청드립니다.',
    requestedDate: '2025-01-08',
    targetChangeDate: '2025-02-01',
    processedAt: '2025-01-09T14:20:00',
    approvedByName: '박코치',
    rejectionReason: '현재 완강 전이라 변경이 불가능합니다. 완강 후 재신청 부탁드립니다.',
  },
];
